version: '2.1'
volumes:
    resin-data:
services:
  core:
    container_name: core
    build: core
    volumes:
      - 'resin-data:/data'
    privileged: true
    labels:
      io.resin.features.dbus: '1'
    ports:
      - "80:80"